#!/bin/bash

##########################################################################
### Problem specific
##########################################################################
#myproblem='../calcium/calcium'
#myproblemshort='calcium'
#NT=48000;
#NTPERU=24000;

myproblem='lotka'
myproblemshort='lotka'
NT=48000;
NTPERU=6000; #24000;
#NT=480;
#NTPERU=48;

##########################################################################
### General functions, output for ampl and such
##########################################################################
writeOutput()
{
	echo "if (match (solve_message, \"infeasible\") > 0) or (match (solve_message, \"presolve\") > 0) then {" >> $filename
	echo "	printf \"Infeasible %.8lg\\n\", _total_solve_time >> "$outfile";" >> $filename
	echo "}" >> $filename
	echo "else if (match (solve_message, \"Maximum\") > 0) then {" >> $filename
	echo "	printf \"Maxiter %.8lg\\n\", _total_solve_time >> "$outfile";" >> $filename
	echo "}" >> $filename
	echo "else {" >> $filename
	echo "	printf \"%.8lg %.8lg\\n\", objective, _total_solve_time >> "$outfile";" >> $filename
	echo "}" >> $filename
	echo " " >> $filename
}

RunSUR()
{
	echo "let mode := \"SUR\";" >> $filename
	echo "include ../algRound.run;" >> $filename
}

RunRelaxed()
{
	echo "let mode := \"Relaxed\";" >> $filename
#	echo "let integrator := \"radau3\";" >> $filename
	echo "let integrator := \"explicitEuler\";" >> $filename
	echo "include ../solve.run;" >> $filename
}

RunRelaxedSim()
{
	echo "let mode := \"Simulate\";" >> $filename
	echo "let integrator := \"explicitEuler\";" >> $filename
	echo "include ../solve.run;" >> $filename
}

RunSTO()
{
	echo "let mode := \"STO\";" >> $filename
	echo "let integrator := \"explicitEuler\";" >> $filename
	echo "include ../solve.run;" >> $filename
}

RunSTOsim()
{
	echo "let mode := \"SimulateSTO\";" >> $filename
	echo "let integrator := \"explicitEuler\";" >> $filename
	echo "include ../solve.run;" >> $filename
}

writeDatfileCommon()
{
	cp -f $myproblem.dat $datfile
	echo "let nt := "$1";" >> $datfile
	echo "let ntperu := "$2";" >> $datfile
}

writeDatfileFixed()
{
	writeDatfileCommon $2 $3
	echo "let {i in IU} wi[1,i] := "$1";" >> $datfile
}

writeDatfileRandom()
{
	writeDatfileCommon $2 $3
	echo "option randseed "$1";" >> $datfile
	echo "let {i in IU} wi[1,i] := Uniform01();" >> $datfile
	echo "let {k in 1..nxd-1, i in I} x[k,i] := xtilde[k];" >> $datfile
	echo "let {i in I} x[nxd,i] := 0;" >> $datfile  # Special assumption: x(nxd) is Mayer term
#	echo "let {k in 1..nxd, i in I} x[k,i] := Uniform01();" >> $datfile
}

writeDatfile()
{
	if [ $i -le 9 ]
		then writeDatfileFixed "0.0"$i $NT $NTPERU
	elif [ $i -le 99 ]
		then writeDatfileFixed "0."$i $NT $NTPERU
	elif [ $i -le 100 ]
		then writeDatfileFixed "1.0" $NT $NTPERU
	elif [ $i -le 201 ]
		then writeDatfileRandom $i $NT $NTPERU
	fi
}

writeHeader()
{
	echo "model ../mintocPre.mod;" > $filename
	echo "model "$myproblem".mod;" >> $filename
	echo "model ../mintocPost.mod;" >> $filename
	echo "data "$datfile";" >> $filename
	echo >> $filename
	#echo "let nlpsolver := \"snopt\";" >> $filename
	echo "let nlpsolver := \"ipopt\";" >> $filename
}

determineIterations()
{
	grep 'Number of Iterations' 'log/'$myproblemshort$approach$NT$NTPERU'_I'$i'.log' > 'log/iter'$myproblemshort$NT$NTPERU'.txt'
	while read line; do
		echo $line >> $outfile
	done < 'log/iter'$myproblemshort$NT$NTPERU'.txt'
}

##########################################################################
### Approach specific
##########################################################################
initNames()
{
	filename='automatic'$myproblemshort$approach'_'$NT'_'$NTPERU'.run'
	datfile='automatic'$myproblemshort$approach'_'$NT'_'$NTPERU'.dat'
	#outfile='out/'$myproblemshort'out'$approach'.dat'
	outfile='optresults/'$myproblemshort'_'$NT'_'$NTPERU'/'$myproblemshort'out'$approach'.dat'

	rm -f $outfile $datfile $filename;
}

runAMPL()
{
	stdbuf -oL timeout 62m ampl $filename > 'log/'$myproblemshort$approach$NT$NTPERU'_I'$i'.log'
	timeoutput=$?
	determineIterations

	#		Check if time limit is violated
	if [ $timeoutput -eq 124 ]
		then echo "TimeLimit" >> $outfile
#	else
#		echo $timeoutput
	fi
}

# POC initialized xtilde, then STO
runPOCSTO1()
{
	writeDatfile

	writeHeader
	RunRelaxed
	writeOutput
	RunSTO
	writeOutput

	runAMPL
}

# POC initialized xtilde
runPOC1()
{
	writeDatfile

	writeHeader
	RunRelaxed
	writeOutput

	runAMPL
}

# STO initialized xtilde
runSTO1()
{
	writeDatfile

	writeHeader
	RunSTO
	writeOutput

	runAMPL
}

# POC initialized by single shooting
runPOC2()
{
	writeDatfile

	writeHeader
	RunRelaxedSim
	RunRelaxed
	writeOutput

	runAMPL
}

# STO initialized by single shooting
runSTO2()
{
	writeDatfile

	writeHeader
	RunSTOsim
	RunSTO
	writeOutput

	runAMPL
}

		

##########################################################################
##########################################################################
### Main loop 
##########################################################################
##########################################################################

approach='POC2'
initNames

for i in {101..200..1}
	do
		echo "Initialization "$i >> $outfile; echo "Initialization "$i 
		runPOC2
	done

approach='STO2'
initNames

for i in {101..200..1}
	do
		echo "Initialization "$i >> $outfile; echo "Initialization "$i 
		runSTO2
	done

approach='POC1'
initNames

for i in {101..200..1}
	do
		echo "Initialization "$i >> $outfile; echo "Initialization "$i 
		runPOC1
	done

approach='POCSTO1'
initNames

for i in {101..101..1}
	do
		echo "Initialization "$i >> $outfile; echo "Initialization "$i 
		runPOCSTO1
	done

approach='STO1'
initNames

for i in {101..200..1}
	do
		echo "Initialization "$i >> $outfile; echo "Initialization "$i 
		runSTO1
	done


